# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main
pr:
- pr

pool: 
  name: Default
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- script: |
    dir d:\learningsupport\
  displayName: 'Show me the folder'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      Write-Host $ENV:myname
  displayName: 'Powershell run'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'


    
  

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies!!!'

- script: |
    python --version
  displayName: 'Python version'
  
- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
